.\"                                      Hey, EMACS: -*- nroff -*-
.TH POTOOL 1 "September 21, 2007"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
potool \- program for manipulating gettext po files
.SH SYNOPSIS
.B potool
.RI FILENAME1
.RI [ " FILENAME2 " ]
.RI [\-f " f|nf|t|nt|nth|o|no"]
.RI [\-n " ctxt|id|str|cmt|ucmt|pcmt|scmt|dcmt|tr|linf"]...
.RI [\-s]
.RI [\-c]
.sp
.B potool
.RI \-h
.SH DESCRIPTION
.B potool
works in two (so far) modes. The first mode requires providing one
file name, and works as a filter. In the second mode, the program
.I replaces
the translations in
.RI FILENAME1
with the translations from
.RI FILENAME2.
(So FILENAME1 is the base po file, while FILENAME2 is our working copy.)
.SH OPTIONS
.TP
.B \-f filter
Determines which po file entries should be
.I retained.
In the second mode, the filters are applied only to
.RI FILENAME2
(the working copy).
Existing filters are:
.br
t   \- translated entries
.br
nt  \- untranslated entries
.br
nth \- untranslated entries and the header
.br
f   \- fuzzy entries
.br
nf  \- entries that are not fuzzy
.br
o   \- obsolete entries
.br
no  \- non-obsolete entries
.br
It is possible to stack filters, by specifying multiple -f options.
.TP
.B \-n filter
Determines which po file entries parts should
.I not
be retained. Any number of -n options is allowed. Valid parameters are:
.br
ctxt  \- don't write 'ctxt' parts
.br
id    \- don't write 'id' parts
.br
str   \- don't write 'str' parts
.br
tr    \- don't write translations
.br
ucmt  \- don't write user's comments
.br
pcmt  \- don't write the comments regarding position in source files
.br
scmt  \- don't write special comments ('#, fuzzy, c-format, ...')
.br
dcmt  \- don't write reserved comments (usually starting with a dot)
.br
cmt   \- don't write any comments
.br
linf  \- change source line numbers to '1'.
.sp
The last parameter is useful when you need to compare two po or pot files using
.BR diff (1)
as it usually returns lots of unimportant line number changes otherwise.
.TP
.B \-s
Don't display the entries themselves, only their count.
.TP
.B \-c
Overwrite all msgstrs with their msgids.
.TP
.B \-h
Display short usage help.
.SH EXAMPLES
.TP
potool x.po -s -ft
displays the number of translated entries. See also
.BR postats (1).
.TP
potool x.po -nstr
Deletes all translations - so you can start from scratch! :-)
.TP
potool x.po -ft && potool x.po -fnt
displays firstly the translated and then the non-translated entries from file x.po
(reverse order is not recommended because of the first "header" entry).
The output contains all information from x.po, with the difference that
untranslated entries are located together in a single place.
.TP
potool x.po -fnt > tmp.po && editor tmp.po && potool x.po tmp.po
lets you easily add new translations, without looking at the already translated
entries
.P
The last two examples are implemented as the
.BR potooledit (1)
program.
.SH SEE ALSO
.BR potooledit (1),
.BR postats (1),
.BR msgmerge (1),
.BR msgfmt (1).
.br
.SH AUTHOR
Potool was written by
.nh
Zbigniew Chyla
.hy
and is now being maintained by
.nh
Marcin Owsiany <porridge@debian.org>.
