#!/bin/bash
set -e
for dir in 1
do
	echo TESTING $dir/no filter
	${WRAPPER} ../potool $dir/in.po | diff -u $dir/in.po -
	(cd $dir && ls -1 | egrep -v '^(in.po|CVS)$') | while read out
	do
		echo "TESTING $dir/${out/.po}"
		${WRAPPER} ../potool -${out/.po} $dir/in.po | diff -u $dir/"${out}" -
	done
done

for dir in 2
do
	echo TESTING $dir/work.po
	${WRAPPER} ../potool $dir/in.po $dir/work.po | diff -u $dir/work.po -
done

for dir in 3
do
	function poedit_test()
	{
		local desc="$1"; shift
		local opts="$1"; shift

		echo TESTING $dir with "$desc"
		cp $dir/in.po $dir/work.po
		PATH="$(pwd)/../scripts:$(pwd)/../:$PATH" EDITOR=: poedit $opts $dir/work.po
		diff -u $dir/in.po $dir/work.po
		rm -f $dir/work.po
	}
	poedit_test "no options" ""
	poedit_test "-a" "-a"
done
